name: slcloudapppro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dropdown_search: ^5.0.6
  connectivity_plus: ^5.0.2
  pdf: ^3.10.7
  printing: ^5.12.0
  intl: ^0.19.0
  geolocator: ^12.0.0

  cupertino_icons: ^1.0.8
  http: ^1.1.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  signalr_core: ^1.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

  # To add assets to your application, uncomment and use the following:
  # assets:
  #   - assets/images/

  # To add custom fonts, uncomment and use the following:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
